In [1]:
import pandas as pd
import numpy as np
import torch

from lagnet import run

In [2]:
A = torch.tensor([[0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1],
                  [0, 0, 0, 0]])

X = torch.tensor([[4, 5],
                  [1, 2],
                  [0, 3],
                  [7, 10]])

In [3]:
res = run(A, X, L=6, K=4, d=10, target=1)

Epoch 0 (0.00 seconds): train loss 34.87
Epoch 1 (0.00 seconds): train loss 34.67
Epoch 2 (0.00 seconds): train loss 34.50
Epoch 3 (0.00 seconds): train loss 34.33
Epoch 4 (0.00 seconds): train loss 34.16
Epoch 5 (0.00 seconds): train loss 34.00
Epoch 6 (0.00 seconds): train loss 33.85
Epoch 7 (0.00 seconds): train loss 33.72
Epoch 8 (0.00 seconds): train loss 33.58
Epoch 9 (0.00 seconds): train loss 33.45
Epoch 10 (0.00 seconds): train loss 33.31
Epoch 11 (0.00 seconds): train loss 33.18
Epoch 12 (0.00 seconds): train loss 33.04
Epoch 13 (0.00 seconds): train loss 32.90
Epoch 14 (0.00 seconds): train loss 32.77
Epoch 15 (0.00 seconds): train loss 32.63
Epoch 16 (0.00 seconds): train loss 32.50
Epoch 17 (0.00 seconds): train loss 32.36
Epoch 18 (0.00 seconds): train loss 32.22
Epoch 19 (0.00 seconds): train loss 32.07
Total Time: 0.027060985565185547 seconds


In [4]:
for param in res:
    print(param)

Parameter containing:
tensor([[ 0.3829, -0.2936],
        [-0.1573,  0.3148],
        [-0.6456,  0.4441],
        [-0.1248,  0.3796],
        [ 0.0833, -0.1008],
        [ 0.1765,  0.0156],
        [ 0.2671, -0.2557],
        [-0.0311, -0.0439],
        [ 0.1025,  0.0127],
        [ 0.5988,  0.2025]], requires_grad=True)
Parameter containing:
tensor([-0.2448, -0.4433, -0.0984, -0.2852, -0.2062,  0.0146,  0.4412,  0.4040,
        -0.6757,  0.4207], requires_grad=True)
Parameter containing:
tensor([[ 0.2161,  0.6892],
        [ 0.4526, -0.6584],
        [-0.6723, -0.3411],
        [ 0.6408, -0.0980],
        [ 0.3206, -0.3106],
        [ 0.6760, -0.3173],
        [ 0.5497,  0.0277],
        [-0.3540,  0.3820],
        [-0.3598,  0.2235],
        [-0.2208, -0.0940]], requires_grad=True)
Parameter containing:
tensor([-0.6613, -0.3534,  0.4039, -0.1520,  0.7247,  0.5476, -0.0134, -0.4523,
         0.4461,  0.2018], requires_grad=True)
Parameter containing:
tensor([[-0.4571,  0.4593],
      